FROM maven:3.8.3-jdk-8-slim AS springbuild

WORKDIR /app

COPY pom.xml .

COPY src ./src

RUN mvn clean install -DskipTests

RUN mvn package -DskipTests

FROM openjdk:8-jre-slim

ENV DB_URL="jdbc:mysql://localhost:3306/diary?useSSL=false&serverTimezone=UTC" \
    DB_USERNAME="diary_db" \
    DB_PASSWORD="root" \
    SPRING_PROFILES_ACTIVE="production" \
    PORT=8080

WORKDIR /app

COPY --from=springbuild /app/target/*.jar ./

RUN dir 

CMD ["java", "-jar", "bookster-0.7.0.jar"]

EXPOSE 8080