spring: 
  profiles: 
    active: production
  application:
    name: bookster
  datasource:
    url: jdbc:mysql://localhost:3306/bookster_db
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: false
    generate-ddl: false
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: pancisin.patrick@gmail.com
    password: Papancisin1
    properties:
      mail:
        smtp:
          auth: true,
          starttls:
            enable: true
jwt: 
  header: Authorization
  secret: 4gB5UWoHNiJg47PE8J44ke6Pn728UZXi
storage:
  path: /files/
                    
---
spring:
  profiles: local
  datasource: 
    username: root
    password: 
server: 
  port: 8180
---
spring: 
  profiles: production
  datasource:
    username: bookster_db
    password: FMDg3bjHvBg87Oxw
server: 
  port: 8080
  