spring: 
  profiles: 
    active: production
  application:
    name: employger
  datasource:
    url: jdbc:mysql://localhost:3306/employger_db
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    generate-ddl: false
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
jwt: 
  header: Authorization
  secret: h02n40Vw37q67650661mZA87rGh17Xk8
  
---
spring:
  profiles: local
  datasource: 
    username: root
    password: 
server: 
  port: 8180
---
spring: 
  profiles: production
  datasource:
    username: employger_db
    password: 0NvnFaG7Uik1bkB6
server: 
  port: 8080
  