spring: 
  profiles: 
    active: production
  application:
    name: bookster
  datasource:
    url: jdbc:mysql://localhost:3306/bookster_db?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
  jpa: 
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: false
    generate-ddl: false
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://104.251.219.31:8080/bookster-auth/oauth/token
      userAuthorizationUri: http://104.251.219.31:8080/bookster-auth/oauth/authorize
    resource:
      userInfoUri: http://104.251.219.31:8080/bookster-auth/user/me
paylane:
  api_key: 45e4f38452d71554195c13f0acee84962fb82a13
  
mailjet: 
  username: 80c51a39aa13ea96c2ecc26bdeb11baf
  password: 3ec24bb92abc4709089069778f2f18b8
  
jwt: 
  header: Authorization
  secret: 4gB5UWoHNiJg47PE8J44ke6Pn728UZXi
  verificationSecret: 123456789

zuul:
  routes:
    user:
      path: /user/**
      url: http://104.251.219.31:8080/bookster-auth/user
---
spring:
  profiles: local
  datasource: 
    username: root
    password: 
  jpa:
    properties:
      hibernate:
        search: 
          default:
            directory_provider: filesystem
            indexBase: /files/lucene/indexes
    show-sql: true
  mail:
    host: localhost
    port: 25
server: 
  port: 8180
storage:
  path: /files/
mailing:
  enabled: true
---
spring: 
  profiles: production
  datasource:
    username: bookster_db
    password: FMDg3bjHvBg87Oxw
  jpa:
    properties:
      hibernate:
        search: 
          default:
            directory_provider: filesystem
            indexBase: /uploads/lucene/indexes
  mail:
    host: localhost
server: 
  port: 8080
storage:
  path: /uploads/bookster/
mailing: 
  enabled: true
  