export const SET_CONFERENCES = 'SET_CONFERENCES';
export const LOADING_CONFERENCES = 'LOADING_CONFERENCES';
export const UPDATE_CONFERENCE = 'UPDATE_CONFERENCE';
export const ADD_CONFERENCE = 'ADD_CONFERENCE';
export const REMOVE_CONFERENCE = 'REMOVE_CONFERENCE';

export const SET_PAGES = 'SET_PAGES';
export const LOADING_PAGES = 'LOADING_PAGES';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const ADD_PAGE = 'ADD_PAGE';
export const REMOVE_PAGE = 'REMOVE_PAGE';

export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const SET_LOCALES = 'SET_LOCALES';

export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const SET_CONTACTS = 'SET_CONTACTS';
export const SET_FOLLOWED_PAGES = 'SET_FOLLOWED_PAGES';

export const ADD_TOAST = 'ADD_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CATEGORIES_LOADING = 'SET_CATEGORIES_LOADING';
export const SET_BRANCHES = 'SET_BRANCHES';
export const SET_BRANCHES_LOADING = 'SET_BRANCHES_LOADING';

export const SET_ATTENDING_EVENTS = 'SET_ATTENDING_EVENTS';
